# Generated by scripts/publish-packages.sh from
# packaging/templates/flake.nix.tmpl for Swift Salamander 0.8.77.
# Edit the template, not this file.
{
  description = "Swift Salamander, a dual-pane file manager for macOS";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";

  outputs =
    { self, nixpkgs }:
    let
      # Swift Salamander ships one build, for Apple silicon. There is no
      # x86_64-darwin output because there is no x86_64-darwin disk image.
      system = "aarch64-darwin";

      # The bundle is proprietary: a free tier plus a one-time Pro purchase.
      # By nixpkgs' definition that is unfree, and an unfree package normally
      # refuses to evaluate until the user sets NIXPKGS_ALLOW_UNFREE. Setting
      # the flag on the nixpkgs imported HERE keeps that out of the user's way,
      # so `nix run github:c0desurfer/swift-salamander-nix` works as the first
      # command somebody types. It applies to this flake's own package set and
      # to nothing else on their machine.
      pkgs = import nixpkgs {
        inherit system;
        config.allowUnfree = true;
      };

      mkSwiftSalamander =
        p:
        p.stdenvNoCC.mkDerivation (finalAttrs: {
          pname = "swift-salamander";
          version = "0.8.77";

          src = p.fetchurl {
            url = "https://cdn.codesurfer.ch/swift-salamander/SwiftSalamander_${finalAttrs.version}_arm64.dmg";
            hash = "sha256-HNmGA+7Vb1SdJbalzA+igdkFGSm0vz7HFd5OpVaYhv8=";
          };

          nativeBuildInputs = [ p.undmg ];

          # undmg's setup hook unpacks the disk image into the build directory,
          # which then holds the bundle beside the usual disk image furniture.
          sourceRoot = ".";

          installPhase = ''
            runHook preInstall

            mkdir -p "$out/Applications"
            cp -R "Swift Salamander.app" "$out/Applications/"

            # A launcher for `nix run` and for anybody who wants the app on
            # PATH. It execs the real executable inside the bundle rather than
            # symlinking it, because macOS works out where a bundle's resources
            # live from the path the process was executed with, and a symlink
            # from $out/bin would point that answer at the wrong directory.
            mkdir -p "$out/bin"
            cat > "$out/bin/swift-salamander" <<EOF
            #!/bin/sh
            exec "$out/Applications/Swift Salamander.app/Contents/MacOS/swift-salamander" "\$@"
            EOF
            chmod +x "$out/bin/swift-salamander"

            runHook postInstall
          '';

          # The bundle arrives code signed, notarized and stapled, and it has
          # to arrive byte for byte. Every fixup Nix would normally run on a
          # Mach-O file rewrites the binary and breaks that signature, so all
          # of them are off: no strip, no install_name_tool, no shebang
          # patching, nothing.
          dontFixup = true;

          meta = {
            description = "Dual-pane file manager for local folders and network storage";
            homepage = "https://salamander.codesurfer.ch/";
            license = p.lib.licenses.unfree;
            sourceProvenance = [ p.lib.sourceTypes.binaryNativeCode ];
            platforms = [ "aarch64-darwin" ];
            mainProgram = "swift-salamander";
          };
        });

      swift-salamander = mkSwiftSalamander pkgs;
    in
    {
      packages.${system} = {
        default = swift-salamander;
        swift-salamander = swift-salamander;
      };

      apps.${system}.default = {
        type = "app";
        program = "${swift-salamander}/bin/swift-salamander";
        meta = swift-salamander.meta;
      };

      # For a nix-darwin or home-manager configuration that would rather pull
      # the package into its own package set than depend on this flake's.
      overlays.default = final: _prev: {
        swift-salamander = mkSwiftSalamander final;
      };

      checks.${system}.build = swift-salamander;

      formatter.${system} = pkgs.nixfmt;
    };
}
